[build]
  command = "npm run build"
  commandOrigin = "config"
  publish = "/opt/build/repo/dist"
  publishOrigin = "config"

[dev]
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
